export const COMPANY_RESEARCH_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "officialWebsite",
    "businessSummary",
    "industry",
    "subindustry",
    "employeeLow",
    "employeeHigh",
    "employeeConfidence",
    "serviceRegions",
    "businessModels",
    "technologies",
    "decisionRoles",
    "commercialFitScore",
    "buyingIntentScore",
    "budgetFitScore",
    "timingScore",
    "needScore",
    "evidenceConfidence",
    "overallPotentialScore",
    "estimatedConversionPercent",
    "assessmentSummary",
    "whyFit",
    "whyNow",
    "risks",
    "recommendedContactRole",
    "nextAction",
    "observations",
  ],
  properties: {
    officialWebsite: { type: "string" },
    businessSummary: { type: "string" },
    industry: { type: "string" },
    subindustry: { type: "string" },
    employeeLow: { type: "integer", minimum: -1 },
    employeeHigh: { type: "integer", minimum: -1 },
    employeeConfidence: { type: "number", minimum: 0, maximum: 1 },
    serviceRegions: { type: "array", items: { type: "string" } },
    businessModels: { type: "array", items: { type: "string" } },
    technologies: { type: "array", items: { type: "string" } },
    decisionRoles: { type: "array", items: { type: "string" } },
    commercialFitScore: { type: "integer", minimum: 0, maximum: 100 },
    buyingIntentScore: { type: "integer", minimum: 0, maximum: 100 },
    budgetFitScore: { type: "integer", minimum: 0, maximum: 100 },
    timingScore: { type: "integer", minimum: 0, maximum: 100 },
    needScore: { type: "integer", minimum: 0, maximum: 100 },
    evidenceConfidence: { type: "integer", minimum: 0, maximum: 100 },
    overallPotentialScore: { type: "integer", minimum: 0, maximum: 100 },
    estimatedConversionPercent: { type: "integer", minimum: 0, maximum: 100 },
    assessmentSummary: { type: "string" },
    whyFit: { type: "array", items: { type: "string" } },
    whyNow: { type: "array", items: { type: "string" } },
    risks: { type: "array", items: { type: "string" } },
    recommendedContactRole: { type: "string" },
    nextAction: { type: "string" },
    observations: {
      type: "array",
      maxItems: 10,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "sourceType",
          "sourceTitle",
          "sourceUrl",
          "title",
          "observation",
          "observedAt",
          "confidence",
          "verificationStatus",
          "signalType",
          "signalStrength",
          "signalRationale",
        ],
        properties: {
          sourceType: {
            type: "string",
            enum: [
              "COMPANY_WEBSITE",
              "NEWS",
              "JOB_BOARD",
              "TENDER",
              "REGISTRY",
              "OTHER",
            ],
          },
          sourceTitle: { type: "string" },
          sourceUrl: { type: "string" },
          title: { type: "string" },
          observation: { type: "string" },
          observedAt: { type: "string" },
          confidence: { type: "number", minimum: 0, maximum: 1 },
          verificationStatus: {
            type: "string",
            enum: ["CONFIRMED", "LIKELY", "UNVERIFIED", "OUTDATED"],
          },
          signalType: {
            type: "string",
            enum: [
              "NONE",
              "HIRING",
              "EXPANSION",
              "FUNDING",
              "LEADERSHIP",
              "TECHNOLOGY",
              "OPERATIONAL_PAIN",
              "GROWTH",
              "PROCUREMENT",
            ],
          },
          signalStrength: { type: "integer", minimum: 0, maximum: 100 },
          signalRationale: { type: "string" },
        },
      },
    },
  },
} as const;
